"""Tests for the version API route."""

from fastapi.testclient import TestClient
from pytest_mock import MockerFixture

from lightly_studio.api.routes.api.status import HTTP_STATUS_OK


def test_get_version(test_client: TestClient, mocker: MockerFixture) -> None:
    mocker.patch(
        "lightly_studio.api.routes.api.version._load_version_info_from_file",
        return_value=("1.2.3", "abc1234"),
    )
    get_version_info_mock = mocker.patch(
        "lightly_studio.api.routes.api.version.get_version_info",
        return_value={
            "version": "9.9.9",
            "git_sha": "fallback",
            "is_tagged_commit": True,
            "_comment": "fallback",
        },
    )

    response = test_client.get("/api/version")

    assert response.status_code == HTTP_STATUS_OK
    assert response.json() == {
        "version": "1.2.3",
        "git_sha": "abc1234",
    }
    get_version_info_mock.assert_not_called()


def test_get_version_falls_back_to_runtime_version(
    test_client: TestClient, mocker: MockerFixture
) -> None:
    mocker.patch(
        "lightly_studio.api.routes.api.version._load_version_info_from_file", return_value=None
    )
    get_version_info_mock = mocker.patch(
        "lightly_studio.api.routes.api.version.get_version_info",
        return_value={
            "version": "1.2.3",
            "git_sha": "abc1234",
            "is_tagged_commit": False,
            "_comment": "Autogenerated by export_version.py. Do not edit manually.",
        },
    )

    response = test_client.get("/api/version")

    assert response.status_code == HTTP_STATUS_OK
    assert response.json() == {
        "version": "1.2.3",
        "git_sha": "abc1234",
    }
    get_version_info_mock.assert_called_once()
