"""add_foreign_key_indexes.

Revision ID: dc6fddd82c1c
Revises: eeb98e205e86
Create Date: 2026-06-15 15:51:16.338889

"""

from collections.abc import Sequence
from typing import Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "dc6fddd82c1c"
down_revision: Union[str, Sequence[str], None] = "eeb98e205e86"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_annotation_base_annotation_label_id"),
        "annotation_base",
        ["annotation_label_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_annotation_base_object_track_id"),
        "annotation_base",
        ["object_track_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_annotation_base_parent_sample_id"),
        "annotation_base",
        ["parent_sample_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_annotation_collection_coverage_parent_sample_id"),
        "annotation_collection_coverage",
        ["parent_sample_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_caption_parent_sample_id"), "caption", ["parent_sample_id"], unique=False
    )
    op.create_index(
        op.f("ix_embedding_model_collection_id"), "embedding_model", ["collection_id"], unique=False
    )
    op.create_index(
        op.f("ix_evaluation_run_gt_annotation_collection_id"),
        "evaluation_run",
        ["gt_annotation_collection_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_evaluation_run_pred_annotation_collection_id"),
        "evaluation_run",
        ["pred_annotation_collection_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_object_track_dataset_id"), "object_track", ["dataset_id"], unique=False
    )
    op.create_index(op.f("ix_sample_collection_id"), "sample", ["collection_id"], unique=False)
    op.create_index(
        op.f("ix_sample_embedding_embedding_model_id"),
        "sample_embedding",
        ["embedding_model_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_samplegrouplinktable_parent_sample_id"),
        "samplegrouplinktable",
        ["parent_sample_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_sampletaglinktable_tag_id"), "sampletaglinktable", ["tag_id"], unique=False
    )
    op.create_index(
        op.f("ix_video_frame_parent_sample_id"), "video_frame", ["parent_sample_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_video_frame_parent_sample_id"), table_name="video_frame")
    op.drop_index(op.f("ix_sampletaglinktable_tag_id"), table_name="sampletaglinktable")
    op.drop_index(
        op.f("ix_samplegrouplinktable_parent_sample_id"), table_name="samplegrouplinktable"
    )
    op.drop_index(op.f("ix_sample_embedding_embedding_model_id"), table_name="sample_embedding")
    op.drop_index(op.f("ix_sample_collection_id"), table_name="sample")
    op.drop_index(op.f("ix_object_track_dataset_id"), table_name="object_track")
    op.drop_index(
        op.f("ix_evaluation_run_pred_annotation_collection_id"), table_name="evaluation_run"
    )
    op.drop_index(
        op.f("ix_evaluation_run_gt_annotation_collection_id"), table_name="evaluation_run"
    )
    op.drop_index(op.f("ix_embedding_model_collection_id"), table_name="embedding_model")
    op.drop_index(op.f("ix_caption_parent_sample_id"), table_name="caption")
    op.drop_index(
        op.f("ix_annotation_collection_coverage_parent_sample_id"),
        table_name="annotation_collection_coverage",
    )
    op.drop_index(op.f("ix_annotation_base_parent_sample_id"), table_name="annotation_base")
    op.drop_index(op.f("ix_annotation_base_object_track_id"), table_name="annotation_base")
    op.drop_index(op.f("ix_annotation_base_annotation_label_id"), table_name="annotation_base")
    # ### end Alembic commands ###
