"""index_file_path_abs.

Revision ID: 5e256380bbae
Revises: 4687cea2f49d
Create Date: 2026-06-30 09:26:23.663593

"""

from collections.abc import Sequence
from typing import Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5e256380bbae"
down_revision: Union[str, Sequence[str], None] = "4687cea2f49d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f("ix_image_file_path_abs"), "image", ["file_path_abs"], unique=False)
    op.create_index(op.f("ix_video_file_path_abs"), "video", ["file_path_abs"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_video_file_path_abs"), table_name="video")
    op.drop_index(op.f("ix_image_file_path_abs"), table_name="image")
    # ### end Alembic commands ###
