"""Export LightlyStudio version information to JSON file."""

from __future__ import annotations

import argparse
import json
import subprocess
from importlib import metadata
from typing import TypedDict


class VersionInfo(TypedDict):
    """Version information of LightlyStudio."""

    version: str
    """Version from package metadata."""

    git_sha: str
    """Git SHA of the current commit."""

    is_tagged_commit: bool
    """Whether the current commit is tagged with vX.Y.Z where X.Y.Z is the version."""

    _comment: str
    """Documentation comment."""


def get_version_info() -> VersionInfo:
    """Retrieve version information of LightlyStudio."""
    version = metadata.version("lightly-studio")
    head_sha = _rev_parse("HEAD")
    # Release tags are annotated. "^{commit}" gets the tagged commit, not the tag object.
    tag_sha = _rev_parse(f"v{version}^{{commit}}")

    return VersionInfo(
        version=version,
        git_sha=subprocess.check_output(["git", "rev-parse", "--short", "HEAD"], text=True).strip(),
        is_tagged_commit=(tag_sha == head_sha),
        _comment="Autogenerated by export_version.py. Do not edit manually.",
    )


def _rev_parse(rev: str) -> str | None:
    """Get the full SHA of a git revision, or None if it does not exist."""
    try:
        return subprocess.check_output(
            ["git", "rev-parse", "--verify", "--quiet", rev], text=True
        ).strip()
    except subprocess.CalledProcessError:
        return None


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Export LightlyStudio version to a file.")
    parser.add_argument(
        "--output",
        type=str,
        default="version.json",
        help="The output file path for the OpenAPI schema (default: openapi.json).",
    )
    args = parser.parse_args()

    version_info = get_version_info()
    print(version_info)
    with open(args.output, "w") as f:
        json.dump(version_info, f, indent=2)
