"""Export LightlyStudio version information to JSON file."""

import argparse
import json
import subprocess
from importlib import metadata
from typing import TypedDict


class VersionInfo(TypedDict):
    """Version information of LightlyStudio."""

    version: str
    """Version from package metadata."""

    git_sha: str
    """Git SHA of the current commit."""

    is_tagged_commit: bool
    """Whether the current commit is tagged with vX.Y.Z where X.Y.Z is the version."""

    _comment: str
    """Documentation comment."""


def get_version_info() -> VersionInfo:
    """Retrieve version information of LightlyStudio."""
    version = metadata.version("lightly-studio")
    git_sha = _get_commit_sha(rev="HEAD")
    # The version tag does not exist for dev versions
    try:
        tag_sha = _get_commit_sha(rev=f"v{version}")
        is_tagged_commit = tag_sha == git_sha
    except subprocess.CalledProcessError:
        is_tagged_commit = False

    return VersionInfo(
        version=version,
        git_sha=git_sha,
        is_tagged_commit=is_tagged_commit,
        _comment="Autogenerated by export_version.py. Do not edit manually.",
    )


def _get_commit_sha(rev: str) -> str:
    """Get the short SHA of the commit that a git revision points to.

    Raises:
        subprocess.CalledProcessError: If the revision does not exist.
    """
    # Release tags are annotated. "^{commit}" gets the tagged commit, not the tag object.
    return subprocess.check_output(
        ["git", "rev-parse", "--verify", "--quiet", "--short", f"{rev}^{{commit}}"], text=True
    ).strip()


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Export LightlyStudio version to a file.")
    parser.add_argument(
        "--output",
        type=str,
        default="version.json",
        help="The output file path for the OpenAPI schema (default: openapi.json).",
    )
    args = parser.parse_args()

    version_info = get_version_info()
    print(version_info)
    with open(args.output, "w") as f:
        json.dump(version_info, f, indent=2)
