import type { Module } from 'langium';
import {
    createDefaultModule,
    createDefaultSharedModule,
    inject,
    DefaultSharedModuleContext,
    LangiumServices,
    LangiumSharedServices,
    PartialLangiumServices
} from 'langium';
import { DatasetQueryGeneratedModule, DatasetQueryGeneratedSharedModule } from './generated/module.js';
import { HelloLangValidator, HelloLangValidationRegistry } from './hello-lang-validator.js';
import { DatasetQueryHoverProvider } from './dataset-query-hover.js';
import { DatasetQueryCompletionProvider } from './dataset-query-completion.js';

/**
 * Declaration of custom services - add your own service classes here.
 */
export type HelloLangAddedServices = {
    validation: {
        HelloLangValidator: HelloLangValidator
    }
}

/**
 * Union of Langium default services and your custom services - use this as constructor parameter
 * of custom service classes.
 */
export type HelloLangServices = LangiumServices & HelloLangAddedServices

/**
 * Dependency injection module that overrides Langium default services and contributes the
 * declared custom services. The Langium defaults can be partially specified to override only
 * selected services, while the custom services must be fully specified.
 */
export const HelloLangModule: Module<HelloLangServices, PartialLangiumServices & HelloLangAddedServices> = {
    validation: {
        ValidationRegistry: (services) => new HelloLangValidationRegistry(services),
        HelloLangValidator: () => new HelloLangValidator()
    },
    lsp: {
        HoverProvider: (services) => new DatasetQueryHoverProvider(services),
        CompletionProvider: (services) => new DatasetQueryCompletionProvider(services)
    }
};

/**
 * Create the full set of services required by Langium.
 *
 * First inject the shared services by merging two modules:
 *  - Langium default shared services
 *  - Services generated by langium-cli
 *
 * Then inject the language-specific services by merging three modules:
 *  - Langium default language-specific services
 *  - Services generated by langium-cli
 *  - Services specified in this file
 */
export function createHelloLangServices(context: DefaultSharedModuleContext): {
    shared: LangiumSharedServices,
    HelloLang: HelloLangServices
} {
    const shared = inject(
        createDefaultSharedModule(context),
        DatasetQueryGeneratedSharedModule
    );
    const HelloLang = inject(
        createDefaultModule({ shared }),
        DatasetQueryGeneratedModule,
        HelloLangModule
    );
    shared.ServiceRegistry.register(HelloLang);
    return { shared, HelloLang };
}
