import type { Module } from 'langium';
import {
    createDefaultModule,
    createDefaultSharedModule,
    inject,
    DefaultSharedModuleContext,
    LangiumServices,
    LangiumSharedServices,
    PartialLangiumServices
} from 'langium';
import { LightlyQueryGeneratedModule, LightlyQueryGeneratedSharedModule } from './generated/module.js';
import { LightlyQueryValidator, LightlyQueryValidationRegistry } from './lightly-query-validator.js';

/**
 * Declaration of custom services - add your own service classes here.
 */
export type LightlyQueryAddedServices = {
    validation: {
        LightlyQueryValidator: LightlyQueryValidator
    }
}

/**
 * Union of Langium default services and your custom services - use this as constructor parameter
 * of custom service classes.
 */
export type LightlyQueryServices = LangiumServices & LightlyQueryAddedServices

/**
 * Dependency injection module that overrides Langium default services and contributes the
 * declared custom services. The Langium defaults can be partially specified to override only
 * selected services, while the custom services must be fully specified.
 */
export const LightlyQueryModule: Module<LightlyQueryServices, PartialLangiumServices & LightlyQueryAddedServices> = {
    validation: {
        ValidationRegistry: (services) => new LightlyQueryValidationRegistry(services),
        LightlyQueryValidator: () => new LightlyQueryValidator()
    }
};

/**
 * Create the full set of services required by Langium.
 *
 * First inject the shared services by merging two modules:
 *  - Langium default shared services
 *  - Services generated by langium-cli
 *
 * Then inject the language-specific services by merging three modules:
 *  - Langium default language-specific services
 *  - Services generated by langium-cli
 *  - Services specified in this file
 */
export function createLightlyQueryServices(context: DefaultSharedModuleContext): {
    shared: LangiumSharedServices,
    LightlyQuery: LightlyQueryServices
} {
    const shared = inject(
        createDefaultSharedModule(context),
        LightlyQueryGeneratedSharedModule
    );
    const LightlyQuery = inject(
        createDefaultModule({ shared }),
        LightlyQueryGeneratedModule,
        LightlyQueryModule
    );
    shared.ServiceRegistry.register(LightlyQuery);
    return { shared, LightlyQuery };
}
