[pytest]
pythonpath = src
python_files = test_*.py

markers =
    skip_on_postgres: skip test when running with --postgres
    skip_on_duckdb: skip test when running with DuckDB (default)

filterwarnings =
    ignore::UserWarning
    ignore::FutureWarning:mobileclip
    ignore::FutureWarning:timm.models.layers
