[pytest]
pythonpath = src
python_files = test_*.py

markers =
    postgres_only: run the test only on the Postgres backend (skipped under DuckDB)

filterwarnings =
    ignore::UserWarning
    ignore::FutureWarning:mobileclip
    ignore::FutureWarning:timm.models.layers
