### Documentation

# Build docs for the current version.
.PHONY: docs
docs:
	@echo "📚 Building documentation..."
	uv run --group=docs mkdocs build --clean

.PHONY: serve
serve:
	@echo "📚 Building documentation..."
	uv run --group=docs mkdocs serve
