"""Alembic migration environment for PostgreSQL schema management.

Executed on every Alembic CLI invocation (upgrade, revision --autogenerate, etc.).
"""

from __future__ import annotations

import configparser
from logging.config import fileConfig
from pathlib import Path
from typing import Any, Literal, cast

from alembic import context
from alembic.autogenerate.api import AutogenContext
from sqlalchemy import engine, pool
from sqlalchemy.engine import Connection
from sqlmodel import SQLModel

import lightly_studio.api.db_tables  # noqa: F401
from lightly_studio.dataset.env import LIGHTLY_STUDIO_DATABASE_URL
from lightly_studio.db_vector import VectorType
from lightly_studio.migrations.config_utils import (
    configure_database_url,
    ensure_script_location,
)

config = context.config

if config.config_file_name is not None:
    _ini_parser = configparser.ConfigParser()
    _ini_parser.read(config.config_file_name)
    if _ini_parser.has_section("formatters"):
        fileConfig(config.config_file_name)


def _render_item(
    type_: str,
    obj: Any,
    autogen_context: AutogenContext,
) -> str | Literal[False]:
    """Render VectorType as pgvector.Vector in autogenerated migrations.

    Used only by ``revision --autogenerate``; ``upgrade`` does not call this hook.
    """
    if type_ == "type" and isinstance(obj, VectorType):
        autogen_context.imports.add("from pgvector.sqlalchemy import Vector")
        return "Vector()"
    return False


def _run_migrations_on(connection: Connection) -> None:
    """Configure Alembic and run migrations on the given connection."""
    context.configure(
        connection=connection,
        target_metadata=target_metadata,
        compare_type=True,
        render_item=_render_item,
    )

    with context.begin_transaction():
        context.run_migrations()


def run_migrations() -> None:
    """Run migrations against Postgres using a shared connection or sqlalchemy.url."""
    shared_connection = config.attributes.get("connection")
    if shared_connection is not None:
        _run_migrations_on(connection=cast(Connection, shared_connection))
        return

    connectable = engine.engine_from_config(
        config.get_section(config.config_ini_section, {}),
        prefix="sqlalchemy.",
        poolclass=pool.NullPool,
    )

    with connectable.connect() as connection:
        _run_migrations_on(connection=connection)


ensure_script_location(config=config, migrations_dir=Path(__file__).parent)

# Schema autogenerate diffs this metadata against the live Postgres catalog.
target_metadata = SQLModel.metadata

configure_database_url(config=config, engine_url=LIGHTLY_STUDIO_DATABASE_URL)
run_migrations()
