"""Alembic migration environment for PostgreSQL schema management.

Executed on every Alembic CLI invocation (upgrade, revision --autogenerate, etc.).
"""

from __future__ import annotations

import configparser
from logging.config import fileConfig
from pathlib import Path
from typing import Any, Literal, cast

from alembic import context
from alembic.autogenerate.api import AutogenContext
from sqlalchemy import engine_from_config, pool, text
from sqlalchemy.engine import Connection
from sqlmodel import SQLModel

import lightly_studio.api.db_tables  # noqa: F401
from lightly_studio import db_url
from lightly_studio.dataset.env import LIGHTLY_STUDIO_DATABASE_URL
from lightly_studio.db_vector import VectorType

config = context.config

if config.config_file_name is not None:
    _ini_parser = configparser.ConfigParser()
    _ini_parser.read(config.config_file_name)
    if _ini_parser.has_section("formatters"):
        fileConfig(config.config_file_name)


def _ensure_script_location() -> None:
    """Use the migrations package directory when the ini path is for source layouts."""
    script_location = config.get_main_option(name="script_location")
    if script_location is not None and Path(script_location).is_dir():
        return
    # Installed wheels place alembic.ini under lightly_studio/; the dev-only
    # src/lightly_studio/migrations path from alembic.ini does not exist there.
    config.set_main_option(name="script_location", value=str(Path(__file__).parent))


def _configure_database_url() -> None:
    """Set sqlalchemy.url on the Alembic config when not already provided."""
    if config.get_main_option(name="sqlalchemy.url"):
        return

    if LIGHTLY_STUDIO_DATABASE_URL is None:
        raise RuntimeError("LIGHTLY_STUDIO_DATABASE_URL must be set for Alembic migrations.")

    config.set_main_option(
        name="sqlalchemy.url",
        value=db_url.ensure_psycopg3_driver(engine_url=LIGHTLY_STUDIO_DATABASE_URL),
    )


def _render_item(
    type_: str,
    obj: Any,
    autogen_context: AutogenContext,
) -> str | Literal[False]:
    """Render VectorType as pgvector.Vector in autogenerated migrations."""
    if type_ == "type" and isinstance(obj, VectorType):
        autogen_context.imports.add("from pgvector.sqlalchemy import Vector")
        return "Vector()"
    return False


def _configure_context(connection: Connection) -> None:
    """Configure Alembic and run migrations on the given connection."""
    connection.execute(statement=text("CREATE EXTENSION IF NOT EXISTS vector"))
    context.configure(
        connection=connection,
        target_metadata=target_metadata,
        compare_type=False,
        render_item=_render_item,
    )

    with context.begin_transaction():
        context.run_migrations()


def run_migrations() -> None:
    """Run migrations against Postgres (requires ``LIGHTLY_STUDIO_DATABASE_URL``)."""
    shared_connection = config.attributes.get("connection")
    if shared_connection is not None:
        _configure_context(connection=cast(Connection, shared_connection))
        return

    connectable = engine_from_config(
        config.get_section(config.config_ini_section, {}),
        prefix="sqlalchemy.",
        poolclass=pool.NullPool,
    )

    with connectable.connect() as connection:
        connection.execute(statement=text("CREATE EXTENSION IF NOT EXISTS vector"))
        connection.commit()
        context.configure(
            connection=connection,
            target_metadata=target_metadata,
            compare_type=False,
            render_item=_render_item,
        )

        with context.begin_transaction():
            context.run_migrations()


_ensure_script_location()

# Schema autogenerate diffs this metadata against the live Postgres catalog.
target_metadata = SQLModel.metadata

_configure_database_url()
run_migrations()
