import type { LayoutRouteId } from '../routes/$types';

type SampleWithAnnotationParams = {
    sampleId: string;
    collectionId: string;
    annotationId: string;
    annotationIndex?: number;
};

// LayoutRouteId is autogenerated from project structure
export const APP_ROUTES: Record<string, LayoutRouteId> = {
    annotations: '/collections/[collection_id]/annotations',
    samples: '/collections/[collection_id]/samples',
    classifiers: '/collections/[collection_id]/classifiers',
    sampleDetails: '/collections/[collection_id]/samples/[sampleId]/[sampleIndex]',
    sampleDetailsWithoutIndex: '/collections/[collection_id]/samples/[sampleId]',
    annotationDetails:
        '/collections/[collection_id]/annotations/[sampleId]/[annotationId]/[annotationIndex]',
    captions: '/collections/[collection_id]/captions',
    videos: '/collections/[collection_id]/videos',
    frames: '/collections/[collection_id]/frames',
    framesDetails: '/collections/[collection_id]/frames/[sample_id]',
    videoDetails: '/collections/[collection_id]/videos/[sample_id]'
};

export const isSampleDetailsRoute = (routeId: string | null): boolean => {
    return routeId ? routeId == APP_ROUTES.sampleDetails : false;
};

export const isSampleDetailsWithoutIndexRoute = (routeId: string | null): boolean => {
    return routeId ? routeId == APP_ROUTES.sampleDetailsWithoutIndex : false;
};

export const isAnnotationDetailsRoute = (routeId: string | null): boolean => {
    return routeId ? routeId == APP_ROUTES.annotationDetails : false;
};

export const isSamplesRoute = (routeId: string | null): boolean => {
    return routeId ? routeId == APP_ROUTES.samples : false;
};

export const isAnnotationsRoute = (routeId: string | null): boolean => {
    return routeId ? routeId == APP_ROUTES.annotations : false;
};

export const isCaptionsRoute = (routeId: string | null): boolean => {
    return routeId ? routeId == APP_ROUTES.captions : false;
};

export const isVideosRoute = (routeId: string | null): boolean => {
    return routeId ? routeId == APP_ROUTES.videos : false;
};

export const isClassifiersRoute = (routeId: string | null): boolean => {
    return routeId ? routeId == APP_ROUTES.classifiers : false;
};

export const isVideoFramesRoute = (routeId: string | null): boolean => {
    return routeId ? routeId == APP_ROUTES.frames : false;
};

export const routes = {
    home: () => `/`,
    // Collection routes
    collection: {
        home: (collectionId: string) => `/collections/${collectionId}`,
        sample: ({ sampleId, collectionId, sampleIndex }: SampleToSampleParams) => {
            let path = `/collections/${collectionId}/samples/${sampleId}`;

            if (typeof sampleIndex !== 'undefined') {
                path = `${path}/${sampleIndex}`;
            }
            return path;
        },
        sampleWithAnnotation: ({
            sampleId,
            collectionId,
            annotationId,
            annotationIndex
        }: SampleWithAnnotationParams) => {
            return `/collections/${collectionId}/annotations/${sampleId}/${annotationId}/${annotationIndex}`;
        },
        samples: (collectionId: string) => `/collections/${collectionId}/samples`,
        captions: (collectionId: string) => `/collections/${collectionId}/captions`,
        annotations: (collectionId: string) => `/collections/${collectionId}/annotations`,
        classifiers: (collectionId: string) => `/collections/${collectionId}/classifiers`,
        videos: (collectionId: string) => `/collections/${collectionId}/videos`,
        frames: (collectionId: string) => `/collections/${collectionId}/frames`,
        videosDetails: (collectionId: string, sampleId: string, index: number | null = null) => {
            const path = `/collections/${collectionId}/videos/${sampleId}`;

            return index === null ? path : path + `?index=${index}`;
        },
        framesDetails: (collectionId: string, sampleId: string, index: number | null = null) => {
            const path = `/collections/${collectionId}/frames/${sampleId}`;

            return index === null ? path : path + `?index=${index}`;
        },
        groups: (collectionId: string) => `/collections/${collectionId}/groups`
    }
};

type SampleToSampleParams = {
    sampleId: string;
    collectionId: string;
    sampleIndex?: number;
};

export const routeHelpers = {
    toHome: () => routes.home(),
    toCollectionHome: (collectionId: string) => routes.collection.home(collectionId),
    toCaptions: (collectionId: string) => routes.collection.captions(collectionId),
    toSamples: (collectionId: string) => routes.collection.samples(collectionId),
    toAnnotations: (collectionId: string) => routes.collection.annotations(collectionId),
    toSample: (params: SampleToSampleParams) => {
        return routes.collection.sample(params);
    },
    toSampleWithAnnotation: (params: SampleWithAnnotationParams) =>
        routes.collection.sampleWithAnnotation(params),
    toClassifiers: (collectionId: string) => routes.collection.classifiers(collectionId),
    toVideos: (collectionId: string) => {
        return routes.collection.videos(collectionId);
    },
    toFrames: (collectionId: string) => {
        return routes.collection.frames(collectionId);
    },
    toVideosDetails: (collectionId: string, sampleId: string, index: number | null = null) => {
        return routes.collection.videosDetails(collectionId, sampleId, index);
    },
    toFramesDetails: (collectionId: string, sampleId: string, index: number | null = null) => {
        return routes.collection.framesDetails(collectionId, sampleId, index);
    },
    toGroups: (collectionId: string) => {
        return routes.collection.groups(collectionId);
    }
};
