import type { LayoutRouteId } from '../routes/$types';

type SampleWithAnnotationParams = {
    sampleId: string;
    datasetId: string;
    collectionType: string;
    collectionId: string;
    annotationId: string;
    annotationIndex?: number;
};

type SampleToSampleParams = {
    sampleId: string;
    datasetId: string;
    collectionType: string;
    collectionId: string;
    sampleIndex?: number;
};

// LayoutRouteId is autogenerated from project structure
export const APP_ROUTES: Record<string, LayoutRouteId> = {
    annotations: '/datasets/[dataset_id]/[collection_type]/[collection_id]/annotations',
    samples: '/datasets/[dataset_id]/[collection_type]/[collection_id]/samples',
    classifiers: '/datasets/[dataset_id]/[collection_type]/[collection_id]/classifiers',
    sampleDetails: '/datasets/[dataset_id]/[collection_type]/[collection_id]/samples/[sampleId]/[sampleIndex]',
    sampleDetailsWithoutIndex: '/datasets/[dataset_id]/[collection_type]/[collection_id]/samples/[sampleId]',
    annotationDetails:
        '/datasets/[dataset_id]/[collection_type]/[collection_id]/annotations/[sampleId]/[annotationId]/[annotationIndex]',
    captions: '/datasets/[dataset_id]/[collection_type]/[collection_id]/captions',
    videos: '/datasets/[dataset_id]/[collection_type]/[collection_id]/videos',
    frames: '/datasets/[dataset_id]/[collection_type]/[collection_id]/frames',
    framesDetails: '/datasets/[dataset_id]/[collection_type]/[collection_id]/frames/[sample_id]',
    videoDetails: '/datasets/[dataset_id]/[collection_type]/[collection_id]/videos/[sample_id]'
};

export const isSampleDetailsRoute = (routeId: string | null): boolean => {
    return routeId ? routeId == APP_ROUTES.sampleDetails : false;
};

export const isSampleDetailsWithoutIndexRoute = (routeId: string | null): boolean => {
    return routeId ? routeId == APP_ROUTES.sampleDetailsWithoutIndex : false;
};

export const isAnnotationDetailsRoute = (routeId: string | null): boolean => {
    return routeId ? routeId == APP_ROUTES.annotationDetails : false;
};

export const isSamplesRoute = (routeId: string | null): boolean => {
    return routeId ? routeId == APP_ROUTES.samples : false;
};

export const isAnnotationsRoute = (routeId: string | null): boolean => {
    return routeId ? routeId == APP_ROUTES.annotations : false;
};

export const isCaptionsRoute = (routeId: string | null): boolean => {
    return routeId ? routeId == APP_ROUTES.captions : false;
};

export const isVideosRoute = (routeId: string | null): boolean => {
    return routeId ? routeId == APP_ROUTES.videos : false;
};

export const isClassifiersRoute = (routeId: string | null): boolean => {
    return routeId ? routeId == APP_ROUTES.classifiers : false;
};

export const isVideoFramesRoute = (routeId: string | null): boolean => {
    return routeId ? routeId == APP_ROUTES.frames : false;
};

// Route structure: /datasets/{dataset_id}/{collection_type}/{collection_id}
export const routes = {
    home: () => `/`,
    // Collection routes with new structure
    collection: {
        home: (datasetId: string, collectionType: string, collectionId: string) => 
            `/datasets/${datasetId}/${collectionType}/${collectionId}`,
        sample: ({ sampleId, datasetId, collectionType, collectionId, sampleIndex }: SampleToSampleParams) => {
            let path = `/datasets/${datasetId}/${collectionType}/${collectionId}/samples/${sampleId}`;

            if (typeof sampleIndex !== 'undefined') {
                path = `${path}/${sampleIndex}`;
            }
            return path;
        },
        sampleWithAnnotation: ({
            sampleId,
            datasetId,
            collectionType,
            collectionId,
            annotationId,
            annotationIndex
        }: SampleWithAnnotationParams) => {
            return `/datasets/${datasetId}/${collectionType}/${collectionId}/annotations/${sampleId}/${annotationId}/${annotationIndex}`;
        },
        samples: (datasetId: string, collectionType: string, collectionId: string) => 
            `/datasets/${datasetId}/${collectionType}/${collectionId}/samples`,
        captions: (datasetId: string, collectionType: string, collectionId: string) => 
            `/datasets/${datasetId}/${collectionType}/${collectionId}/captions`,
        annotations: (datasetId: string, collectionType: string, collectionId: string) => 
            `/datasets/${datasetId}/${collectionType}/${collectionId}/annotations`,
        classifiers: (datasetId: string, collectionType: string, collectionId: string) => 
            `/datasets/${datasetId}/${collectionType}/${collectionId}/classifiers`,
        videos: (datasetId: string, collectionType: string, collectionId: string) => 
            `/datasets/${datasetId}/${collectionType}/${collectionId}/videos`,
        frames: (datasetId: string, collectionType: string, collectionId: string) => 
            `/datasets/${datasetId}/${collectionType}/${collectionId}/frames`,
        videosDetails: (datasetId: string, collectionType: string, collectionId: string, sampleId: string, index: number | null = null) => {
            const path = `/datasets/${datasetId}/${collectionType}/${collectionId}/videos/${sampleId}`;

            return index === null ? path : path + `?index=${index}`;
        },
        framesDetails: (datasetId: string, collectionType: string, collectionId: string, sampleId: string, index: number | null = null) => {
            const path = `/datasets/${datasetId}/${collectionType}/${collectionId}/frames/${sampleId}`;

            return index === null ? path : path + `?index=${index}`;
        },
        groups: (datasetId: string, collectionType: string, collectionId: string) => 
            `/datasets/${datasetId}/${collectionType}/${collectionId}/groups`
    }
};

export const routeHelpers = {
    toHome: () => routes.home(),
    toCollectionHome: (datasetId: string, collectionType: string, collectionId: string) => 
        routes.collection.home(datasetId, collectionType, collectionId),
    toCaptions: (datasetId: string, collectionType: string, collectionId: string) => 
        routes.collection.captions(datasetId, collectionType, collectionId),
    toSamples: (datasetId: string, collectionType: string, collectionId: string) => 
        routes.collection.samples(datasetId, collectionType, collectionId),
    toAnnotations: (datasetId: string, collectionType: string, collectionId: string) => 
        routes.collection.annotations(datasetId, collectionType, collectionId),
    toSample: (params: SampleToSampleParams) => {
        return routes.collection.sample(params);
    },
    toSampleWithAnnotation: (params: SampleWithAnnotationParams) =>
        routes.collection.sampleWithAnnotation(params),
    toClassifiers: (datasetId: string, collectionType: string, collectionId: string) => 
        routes.collection.classifiers(datasetId, collectionType, collectionId),
    toVideos: (datasetId: string, collectionType: string, collectionId: string) => {
        return routes.collection.videos(datasetId, collectionType, collectionId);
    },
    toFrames: (datasetId: string, collectionType: string, collectionId: string) => {
        return routes.collection.frames(datasetId, collectionType, collectionId);
    },
    toVideosDetails: (datasetId: string, collectionType: string, collectionId: string, sampleId: string, index: number | null = null) => {
        return routes.collection.videosDetails(datasetId, collectionType, collectionId, sampleId, index);
    },
    toFramesDetails: (datasetId: string, collectionType: string, collectionId: string, sampleId: string, index: number | null = null) => {
        return routes.collection.framesDetails(datasetId, collectionType, collectionId, sampleId, index);
    },
    toGroups: (datasetId: string, collectionType: string, collectionId: string) => {
        return routes.collection.groups(datasetId, collectionType, collectionId);
    }
};
