import type { LayoutRouteId } from '../routes/$types';

const COLLECTION_BASE_ROUTE = '/datasets/[dataset_id]/[collection_type]/[collection_id]';

type SampleWithAnnotationParams = {
    datasetId: string;
    collectionType: string;
    collectionId: string;
    annotationId: string;
};

type SampleToSampleParams = {
    sampleId: string;
    datasetId: string;
    collectionType: string;
    collectionId: string;
};

// LayoutRouteId is autogenerated from project structure
export const APP_ROUTES: Record<string, LayoutRouteId> = {
    annotations: `${COLLECTION_BASE_ROUTE}/annotations`,
    samples: `${COLLECTION_BASE_ROUTE}/samples`,
    sampleDetails: `${COLLECTION_BASE_ROUTE}/samples/[sampleId]`,
    annotationDetails: `${COLLECTION_BASE_ROUTE}/annotations/[annotationId]`,
    captions: `${COLLECTION_BASE_ROUTE}/captions`,
    videos: `${COLLECTION_BASE_ROUTE}/videos`,
    frames: `${COLLECTION_BASE_ROUTE}/frames`,
    framesDetails: `${COLLECTION_BASE_ROUTE}/frames/[sample_id]`,
    videoDetails: `${COLLECTION_BASE_ROUTE}/videos/[sample_id]`
};

export const isSampleDetailsRoute = (routeId: string | null): boolean => {
    return routeId ? routeId == APP_ROUTES.sampleDetails : false;
};

export const isAnnotationDetailsRoute = (routeId: string | null): boolean => {
    return routeId ? routeId == APP_ROUTES.annotationDetails : false;
};

export const isSamplesRoute = (routeId: string | null): boolean => {
    return routeId ? routeId == APP_ROUTES.samples : false;
};

export const isAnnotationsRoute = (routeId: string | null): boolean => {
    return routeId ? routeId == APP_ROUTES.annotations : false;
};

export const isCaptionsRoute = (routeId: string | null): boolean => {
    return routeId ? routeId == APP_ROUTES.captions : false;
};

export const isVideosRoute = (routeId: string | null): boolean => {
    return routeId ? routeId == APP_ROUTES.videos : false;
};

export const isVideoFramesRoute = (routeId: string | null): boolean => {
    return routeId ? routeId == APP_ROUTES.frames : false;
};

// Route structure: /datasets/{dataset_id}/{collection_type}/{collection_id}
export const routes = {
    home: () => `/`,
    // Collection routes with new structure
    collection: {
        home: (datasetId: string, collectionType: string, collectionId: string) =>
            `/datasets/${datasetId}/${collectionType}/${collectionId}`,
        sample: ({ sampleId, datasetId, collectionType, collectionId }: SampleToSampleParams) => {
            return `/datasets/${datasetId}/${collectionType}/${collectionId}/samples/${sampleId}`;
        },
        sampleWithAnnotation: ({
            datasetId,
            collectionType,
            collectionId,
            annotationId
        }: SampleWithAnnotationParams) => {
            return `/datasets/${datasetId}/${collectionType}/${collectionId}/annotations/${annotationId}`;
        },
        samples: (datasetId: string, collectionType: string, collectionId: string) =>
            `/datasets/${datasetId}/${collectionType}/${collectionId}/samples`,
        captions: (datasetId: string, collectionType: string, collectionId: string) =>
            `/datasets/${datasetId}/${collectionType}/${collectionId}/captions`,
        annotations: (datasetId: string, collectionType: string, collectionId: string) =>
            `/datasets/${datasetId}/${collectionType}/${collectionId}/annotations`,
        videos: (datasetId: string, collectionType: string, collectionId: string) =>
            `/datasets/${datasetId}/${collectionType}/${collectionId}/videos`,
        frames: (datasetId: string, collectionType: string, collectionId: string) =>
            `/datasets/${datasetId}/${collectionType}/${collectionId}/frames`,
        videosDetails: (
            datasetId: string,
            collectionType: string,
            collectionId: string,
            sampleId: string,
            frameNumber?: number
        ) => {
            const basePath = `/datasets/${datasetId}/${collectionType}/${collectionId}/videos/${sampleId}`;

            const params = new URLSearchParams();

            if (frameNumber !== undefined) {
                params.append('frame_number', String(frameNumber));
            }

            const query = params.toString();

            return query ? `${basePath}?${query}` : basePath;
        },
        framesDetails: (
            datasetId: string,
            collectionType: string,
            collectionId: string,
            sampleId: string,
            index: number | null = null
        ) => {
            const path = `/datasets/${datasetId}/${collectionType}/${collectionId}/frames/${sampleId}`;

            return index === null ? path : path + `?index=${index}`;
        },
        groups: (datasetId: string, collectionType: string, collectionId: string) =>
            `/datasets/${datasetId}/${collectionType}/${collectionId}/groups`
    }
};

export const routeHelpers = {
    toHome: () => routes.home(),
    toCollectionHome: (datasetId: string, collectionType: string, collectionId: string) =>
        routes.collection.home(datasetId, collectionType, collectionId),
    toCaptions: (datasetId: string, collectionType: string, collectionId: string) =>
        routes.collection.captions(datasetId, collectionType, collectionId),
    toSamples: (datasetId: string, collectionType: string, collectionId: string) =>
        routes.collection.samples(datasetId, collectionType, collectionId),
    toAnnotations: (datasetId: string, collectionType: string, collectionId: string) =>
        routes.collection.annotations(datasetId, collectionType, collectionId),
    toSample: (params: SampleToSampleParams) => {
        return routes.collection.sample(params);
    },
    toSampleWithAnnotation: (params: SampleWithAnnotationParams) =>
        routes.collection.sampleWithAnnotation(params),
    toVideos: (datasetId: string, collectionType: string, collectionId: string) => {
        return routes.collection.videos(datasetId, collectionType, collectionId);
    },
    toFrames: (datasetId: string, collectionType: string, collectionId: string) => {
        return routes.collection.frames(datasetId, collectionType, collectionId);
    },
    toVideosDetails: (
        datasetId: string,
        collectionType: string,
        collectionId: string,
        sampleId: string,
        frameNumber?: number
    ) => {
        return routes.collection.videosDetails(
            datasetId,
            collectionType,
            collectionId,
            sampleId,
            frameNumber
        );
    },
    toFramesDetails: (
        datasetId: string,
        collectionType: string,
        collectionId: string,
        sampleId: string,
        index: number | null = null
    ) => {
        return routes.collection.framesDetails(
            datasetId,
            collectionType,
            collectionId,
            sampleId,
            index
        );
    },
    toGroups: (datasetId: string, collectionType: string, collectionId: string) => {
        return routes.collection.groups(datasetId, collectionType, collectionId);
    }
};
